var annotated_dup =
[
    [ "zth", "namespacezth.html", [
      [ "fsm", "namespacezth_1_1fsm.html", [
        [ "Action", "classzth_1_1fsm_1_1_action.html", "classzth_1_1fsm_1_1_action" ],
        [ "BasicFsm", "classzth_1_1fsm_1_1_basic_fsm.html", "classzth_1_1fsm_1_1_basic_fsm" ],
        [ "Callback", "classzth_1_1fsm_1_1_callback.html", null ],
        [ "Callback< T, R, false, false, true >", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01false_00_01false_00_01true_01_4.html", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01false_00_01false_00_01true_01_4" ],
        [ "Callback< T, R, false, true, true >", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01false_00_01true_00_01true_01_4.html", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01false_00_01true_00_01true_01_4" ],
        [ "Callback< T, R, true, false, true >", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01true_00_01false_00_01true_01_4.html", "classzth_1_1fsm_1_1_callback_3_01_t_00_01_r_00_01true_00_01false_00_01true_01_4" ],
        [ "Fsm", "classzth_1_1fsm_1_1_fsm.html", "classzth_1_1fsm_1_1_fsm" ],
        [ "function_traits", "structzth_1_1fsm_1_1function__traits.html", null ],
        [ "Guard", "classzth_1_1fsm_1_1_guard.html", "classzth_1_1fsm_1_1_guard" ],
        [ "GuardedAction", "classzth_1_1fsm_1_1_guarded_action.html", "classzth_1_1fsm_1_1_guarded_action" ],
        [ "GuardedActionBase", "classzth_1_1fsm_1_1_guarded_action_base.html", "classzth_1_1fsm_1_1_guarded_action_base" ],
        [ "GuardPollInterval", "classzth_1_1fsm_1_1_guard_poll_interval.html", "classzth_1_1fsm_1_1_guard_poll_interval" ],
        [ "InputGuard", "classzth_1_1fsm_1_1_input_guard.html", "classzth_1_1fsm_1_1_input_guard" ],
        [ "invalid_fsm", "structzth_1_1fsm_1_1invalid__fsm.html", "structzth_1_1fsm_1_1invalid__fsm" ],
        [ "Named", "classzth_1_1fsm_1_1_named.html", null ],
        [ "Named< false >", "classzth_1_1fsm_1_1_named_3_01false_01_4.html", "classzth_1_1fsm_1_1_named_3_01false_01_4" ],
        [ "Named< true >", "classzth_1_1fsm_1_1_named_3_01true_01_4.html", "classzth_1_1fsm_1_1_named_3_01true_01_4" ],
        [ "Symbol", "classzth_1_1fsm_1_1_symbol.html", "classzth_1_1fsm_1_1_symbol" ],
        [ "Transition", "classzth_1_1fsm_1_1_transition.html", "classzth_1_1fsm_1_1_transition" ],
        [ "Transitions", "classzth_1_1fsm_1_1_transitions.html", "classzth_1_1fsm_1_1_transitions" ],
        [ "TransitionsBase", "classzth_1_1fsm_1_1_transitions_base.html", "classzth_1_1fsm_1_1_transitions_base" ],
        [ "TransitionStart", "classzth_1_1fsm_1_1_transition_start.html", "classzth_1_1fsm_1_1_transition_start" ],
        [ "TypedAction", "classzth_1_1fsm_1_1_typed_action.html", "classzth_1_1fsm_1_1_typed_action" ],
        [ "TypedGuard", "classzth_1_1fsm_1_1_typed_guard.html", "classzth_1_1fsm_1_1_typed_guard" ]
      ] ],
      [ "impl", "namespacezth_1_1impl.html", [
        [ "Arguments", "structzth_1_1impl_1_1_arguments.html", "structzth_1_1impl_1_1_arguments" ],
        [ "ContextArch", "classzth_1_1impl_1_1_context_arch.html", "classzth_1_1impl_1_1_context_arch" ],
        [ "ContextBase", "classzth_1_1impl_1_1_context_base.html", "classzth_1_1impl_1_1_context_base" ],
        [ "FunctionION", "structzth_1_1impl_1_1_function_i_o_n.html", "structzth_1_1impl_1_1_function_i_o_n" ],
        [ "FunctionION< void, A, A_ >", "structzth_1_1impl_1_1_function_i_o_n_3_01void_00_01_a_00_01_a___01_4.html", "structzth_1_1impl_1_1_function_i_o_n_3_01void_00_01_a_00_01_a___01_4" ],
        [ "Packed", "structzth_1_1impl_1_1_packed.html", "structzth_1_1impl_1_1_packed" ],
        [ "Packed< T & >", "structzth_1_1impl_1_1_packed_3_01_t_01_6_01_4.html", "structzth_1_1impl_1_1_packed_3_01_t_01_6_01_4" ],
        [ "std_future_base", "classzth_1_1impl_1_1std__future__base.html", "classzth_1_1impl_1_1std__future__base" ],
        [ "std_promise_base", "classzth_1_1impl_1_1std__promise__base.html", "classzth_1_1impl_1_1std__promise__base" ],
        [ "std_shared_future_base", "classzth_1_1impl_1_1std__shared__future__base.html", "classzth_1_1impl_1_1std__shared__future__base" ]
      ] ],
      [ "AutoFuture", "classzth_1_1_auto_future.html", "classzth_1_1_auto_future" ],
      [ "Backtrace", "classzth_1_1_backtrace.html", "classzth_1_1_backtrace" ],
      [ "choose_type", "structzth_1_1choose__type.html", "structzth_1_1choose__type" ],
      [ "choose_type< void, WhenTIsVoid >", "structzth_1_1choose__type_3_01void_00_01_when_t_is_void_01_4.html", "structzth_1_1choose__type_3_01void_00_01_when_t_is_void_01_4" ],
      [ "Config", "structzth_1_1_config.html", null ],
      [ "Context", "classzth_1_1_context.html", "classzth_1_1_context" ],
      [ "ContextAttr", "structzth_1_1_context_attr.html", "structzth_1_1_context_attr" ],
      [ "cow_string", "classzth_1_1cow__string.html", "classzth_1_1cow__string" ],
      [ "DefaultConfig", "structzth_1_1_default_config.html", "structzth_1_1_default_config" ],
      [ "Env", "structzth_1_1_env.html", null ],
      [ "EventRate", "classzth_1_1_event_rate.html", "classzth_1_1_event_rate" ],
      [ "Fiber", "classzth_1_1_fiber.html", "classzth_1_1_fiber" ],
      [ "fiber_type", "structzth_1_1fiber__type.html", null ],
      [ "fiber_type< R(*)(Args...)>", "structzth_1_1fiber__type_3_01_r_07_5_08_07_args_8_8_8_08_4.html", null ],
      [ "fiber_type_impl", "structzth_1_1fiber__type__impl.html", "structzth_1_1fiber__type__impl" ],
      [ "FiberManipulator", "classzth_1_1_fiber_manipulator.html", "classzth_1_1_fiber_manipulator" ],
      [ "Fsm", "classzth_1_1_fsm.html", "classzth_1_1_fsm" ],
      [ "FsmCallback", "classzth_1_1_fsm_callback.html", "classzth_1_1_fsm_callback" ],
      [ "FsmCallback< State_, void, Input_, FsmImpl_ >", "classzth_1_1_fsm_callback_3_01_state___00_01void_00_01_input___00_01_fsm_impl___01_4.html", "classzth_1_1_fsm_callback_3_01_state___00_01void_00_01_input___00_01_fsm_impl___01_4" ],
      [ "FsmCompiler", "classzth_1_1_fsm_compiler.html", "classzth_1_1_fsm_compiler" ],
      [ "FsmDescription", "structzth_1_1_fsm_description.html", "structzth_1_1_fsm_description" ],
      [ "FsmGuard", "classzth_1_1_fsm_guard.html", "classzth_1_1_fsm_guard" ],
      [ "Future", "classzth_1_1_future.html", "classzth_1_1_future" ],
      [ "Future< void >", "classzth_1_1_future_3_01void_01_4.html", "classzth_1_1_future_3_01void_01_4" ],
      [ "Gate", "classzth_1_1_gate.html", "classzth_1_1_gate" ],
      [ "List", "classzth_1_1_list.html", "classzth_1_1_list" ],
      [ "list_type", "structzth_1_1list__type.html", "structzth_1_1list__type" ],
      [ "Listable", "classzth_1_1_listable.html", "classzth_1_1_listable" ],
      [ "Load", "classzth_1_1_load.html", "classzth_1_1_load" ],
      [ "Locked", "classzth_1_1_locked.html", "classzth_1_1_locked" ],
      [ "map_type", "structzth_1_1map__type.html", "structzth_1_1map__type" ],
      [ "monotonic_clock", "structzth_1_1monotonic__clock.html", "structzth_1_1monotonic__clock" ],
      [ "Mutex", "classzth_1_1_mutex.html", "classzth_1_1_mutex" ],
      [ "passOnExit", "classzth_1_1pass_on_exit.html", "classzth_1_1pass_on_exit" ],
      [ "PerfEvent", "structzth_1_1_perf_event.html", "structzth_1_1_perf_event" ],
      [ "PerfEvent< false >", "structzth_1_1_perf_event_3_01false_01_4.html", "structzth_1_1_perf_event_3_01false_01_4" ],
      [ "PerfFiber", "classzth_1_1_perf_fiber.html", "classzth_1_1_perf_fiber" ],
      [ "PeriodicWakeUp", "classzth_1_1_periodic_wake_up.html", "classzth_1_1_periodic_wake_up" ],
      [ "Pollable", "structzth_1_1_pollable.html", "structzth_1_1_pollable" ],
      [ "PollableFd", "structzth_1_1_pollable_fd.html", "structzth_1_1_pollable_fd" ],
      [ "PolledMemberWaiting", "classzth_1_1_polled_member_waiting.html", "classzth_1_1_polled_member_waiting" ],
      [ "PolledMemberWaitingHelper", "structzth_1_1_polled_member_waiting_helper.html", "structzth_1_1_polled_member_waiting_helper" ],
      [ "PolledWaiting", "classzth_1_1_polled_waiting.html", "classzth_1_1_polled_waiting" ],
      [ "PollerClient", "classzth_1_1_poller_client.html", "classzth_1_1_poller_client" ],
      [ "PollerClientBase", "classzth_1_1_poller_client_base.html", "classzth_1_1_poller_client_base" ],
      [ "PollerInterface", "classzth_1_1_poller_interface.html", "classzth_1_1_poller_interface" ],
      [ "PollerServer", "classzth_1_1_poller_server.html", "classzth_1_1_poller_server" ],
      [ "PollerServerBase", "classzth_1_1_poller_server_base.html", "classzth_1_1_poller_server_base" ],
      [ "RefCounted", "classzth_1_1_ref_counted.html", "classzth_1_1_ref_counted" ],
      [ "Register", "structzth_1_1_register.html", "structzth_1_1_register" ],
      [ "Runnable", "classzth_1_1_runnable.html", "classzth_1_1_runnable" ],
      [ "safe_ptr", "classzth_1_1safe__ptr.html", "classzth_1_1safe__ptr" ],
      [ "Semaphore", "classzth_1_1_semaphore.html", "classzth_1_1_semaphore" ],
      [ "Sequence", "structzth_1_1_sequence.html", null ],
      [ "setName", "classzth_1_1set_name.html", "classzth_1_1set_name" ],
      [ "setStackSize", "classzth_1_1set_stack_size.html", "classzth_1_1set_stack_size" ],
      [ "SharedPointer", "classzth_1_1_shared_pointer.html", "classzth_1_1_shared_pointer" ],
      [ "Signal", "classzth_1_1_signal.html", "classzth_1_1_signal" ],
      [ "Singleton", "classzth_1_1_singleton.html", "classzth_1_1_singleton" ],
      [ "small_vector", "classzth_1_1small__vector.html", "classzth_1_1small__vector" ],
      [ "smallest_uint< x, smallest_uint_size< 1 > >", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_011_01_4_01_4.html", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_011_01_4_01_4" ],
      [ "smallest_uint< x, smallest_uint_size< 2 > >", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_012_01_4_01_4.html", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_012_01_4_01_4" ],
      [ "smallest_uint< x, smallest_uint_size< 4 > >", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_014_01_4_01_4.html", "structzth_1_1smallest__uint_3_01x_00_01smallest__uint__size_3_014_01_4_01_4" ],
      [ "smallest_uint_size", "structzth_1_1smallest__uint__size.html", null ],
      [ "SortedList", "classzth_1_1_sorted_list.html", "classzth_1_1_sorted_list" ],
      [ "Synchronizer", "classzth_1_1_synchronizer.html", "classzth_1_1_synchronizer" ],
      [ "ThreadLocalSingleton", "classzth_1_1_thread_local_singleton.html", "classzth_1_1_thread_local_singleton" ],
      [ "TimedWaitable", "classzth_1_1_timed_waitable.html", "classzth_1_1_timed_waitable" ],
      [ "TimeInterval", "classzth_1_1_time_interval.html", "classzth_1_1_time_interval" ],
      [ "Timestamp", "classzth_1_1_timestamp.html", "classzth_1_1_timestamp" ],
      [ "type", "structzth_1_1type.html", null ],
      [ "TypedFiber", "classzth_1_1_typed_fiber.html", "classzth_1_1_typed_fiber" ],
      [ "TypedFiberFactory", "classzth_1_1_typed_fiber_factory.html", "classzth_1_1_typed_fiber_factory" ],
      [ "TypedFiberN", "classzth_1_1_typed_fiber_n.html", "classzth_1_1_typed_fiber_n" ],
      [ "TypedFiberN< void, Args... >", "classzth_1_1_typed_fiber_n_3_01void_00_01_args_8_8_8_01_4.html", "classzth_1_1_typed_fiber_n_3_01void_00_01_args_8_8_8_01_4" ],
      [ "TypedFiberType", "structzth_1_1_typed_fiber_type.html", null ],
      [ "TypedFiberType< R(*)(Args...)>", "structzth_1_1_typed_fiber_type_3_01_r_07_5_08_07_args_8_8_8_08_4.html", "structzth_1_1_typed_fiber_type_3_01_r_07_5_08_07_args_8_8_8_08_4" ],
      [ "UniqueID", "classzth_1_1_unique_i_d.html", "classzth_1_1_unique_i_d" ],
      [ "UniqueIDBase", "classzth_1_1_unique_i_d_base.html", "classzth_1_1_unique_i_d_base" ],
      [ "vector_type", "structzth_1_1vector__type.html", "structzth_1_1vector__type" ],
      [ "Waitable", "classzth_1_1_waitable.html", "classzth_1_1_waitable" ],
      [ "Waiter", "classzth_1_1_waiter.html", "classzth_1_1_waiter" ],
      [ "Worker", "classzth_1_1_worker.html", "classzth_1_1_worker" ],
      [ "ZmqPoller", "classzth_1_1_zmq_poller.html", "classzth_1_1_zmq_poller" ]
    ] ],
    [ "zth_cond_t", "structzth__cond__t.html", "structzth__cond__t" ],
    [ "zth_future_t", "structzth__future__t.html", "structzth__future__t" ],
    [ "zth_gate_t", "structzth__gate__t.html", "structzth__gate__t" ],
    [ "zth_init_entry", "structzth__init__entry.html", "structzth__init__entry" ],
    [ "zth_mutex_t", "structzth__mutex__t.html", "structzth__mutex__t" ],
    [ "zth_sem_t", "structzth__sem__t.html", "structzth__sem__t" ]
];