# SPDX-FileCopyrightText: 2019-2026 Jochem Rutgers
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "futures"
version = "0.1.0"
edition = "2021"

[features]
default = ["std"]
std = ["zth/std"]
bare-metal = ["zth/bare-metal"]

[dependencies]
zth = { path = "../../../rust", default-features = false }
